name: CI - Python Unit Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      # Tu código fuente está en lab4_tests_example/src
      - name: Set PYTHONPATH to src
        run: echo "PYTHONPATH=$GITHUB_WORKSPACE/lab4_tests_example/src" >> $GITHUB_ENV

      # (Opcional) Diagnóstico por si hay errores de import/colección
      - name: Debug layout and sys.path
        run: |
          python -V
          pwd
          ls -R
          python - << 'PY'
          import os, sys
          print("GITHUB_WORKSPACE:", os.environ.get("GITHUB_WORKSPACE"))
          print("PYTHONPATH:", os.environ.get("PYTHONPATH"))
          print("sys.path:")
          for p in sys.path: print(" -", p)
          PY

      # Tus pruebas están en lab4_tests_example/tests
      - name: Run unittest discovery
        run: python -m unittest discover -v -s lab4_tests_example/tests -p "test_*.py"
