name: CI - Run tests on every commit

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install pytest
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      # Hace importable tu carpeta src dentro del runner de GitHub
      - name: Make src importable
        run: echo "PYTHONPATH=$GITHUB_WORKSPACE/lab4_tests_example/src" >> $GITHUB_ENV

      # Ejecuta pruebas de tu carpeta tests
      - name: Run tests
        run: pytest lab4_tests_example/tests -q
