name: CI - Python Unit Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      # 🔧 CLAVE: que 'src' sea localizable -> PYTHONPATH debe ser la carpeta que contiene 'src'
      - name: Set PYTHONPATH so 'src' is importable
        run: echo "PYTHONPATH=$GITHUB_WORKSPACE/lab4_tests_example" >> $GITHUB_ENV

      # (opcional) diagnóstico rápido por si algo más falla
      - name: Debug layout & sys.path
        run: |
          python -V
          ls -R
          python - << 'PY'
          import os, sys
          print("PYTHONPATH:", os.environ.get("PYTHONPATH"))
          print("sys.path:")
          for p in sys.path: print(" -", p)
          # Sanity import donde fallaba:
          try:
              import src.models.character as _; print("OK: src.models.character")
          except Exception as e:
              print("FAIL: src.models.character ->", repr(e))
          PY

      - name: Run unittest discovery
        run: python -m unittest discover -v -s lab4_tests_example/tests -p "test_*.py"
